server:
  port: 8080
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka
zuul:
  ignoredServices: '*'
  routes:
    app-a:
      path: /u/**
      serviceId: consumer3

