server:
  port: 9192
spring:
  application:
    name: provider #所有生产者的此处应用名称相同，eureka配置类ribbon负载均衡策略才会生效

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka

logging:
  level:
    root: INFO